name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Create wrangler.toml
        env:
          USERNAME: ${{ secrets.USERNAME || '_user' }}
          PASSWORD: ${{ secrets.WORKERS_PASSWORD1 || '_pass' }}
          BUCKET_NAME: ${{ secrets.WORKERS_BUCKET_NAME1 || 'bucket' }}
          WORKERS_NAME: ${{ vars.WORKERS_NAME1 || 'cf-r2-webdav' }}
        run: |
          sed -e "s/\$USERNAME/$USERNAME/g" \
              -e "s/\$PASSWORD/$PASSWORD/g" \
              -e "s/\$BUCKET_NAME/$BUCKET_NAME/g" \
              -e "s/\$WORKERS_NAME/$WORKERS_NAME/g" \
              wrangler.toml.template > wrangler.toml
          cat wrangler.toml

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Create wrangler.toml
        env:
          USERNAME: ${{ secrets.USERNAME || '_user' }}
          PASSWORD: ${{ secrets.WORKERS_PASSWORD2 || '_pass' }}
          BUCKET_NAME: ${{ secrets.WORKERS_BUCKET_NAME2 || 'bucket' }}
          WORKERS_NAME: ${{ vars.WORKERS_NAME2 || 'cf-r2-webdav' }}
        run: |
          sed -e "s/\$USERNAME/$USERNAME/g" \
              -e "s/\$PASSWORD/$PASSWORD/g" \
              -e "s/\$BUCKET_NAME/$BUCKET_NAME/g" \
              -e "s/\$WORKERS_NAME/$WORKERS_NAME/g" \
              wrangler.toml.template > wrangler.toml
          cat wrangler.toml

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
